### ISSUE TITLE
Not an issue, but need help

### ISSUE THREAD

**Issue by adisone** [BasuCert/WinboxPoC#45]
Hello!

I am an absolute beginner with very little previous experience in coding, but I generally know a lot about PCs, networks etc. Can someone explain to me how to actually use this script on windows 10? This guide assumes that you already know a bunch of stuff. Do I type in CMD? In Python? What exactly do I type to get the script going? At my workplace we have a MIKROTIK RouterOS with 6.29.1 version, so the script should work. I just don't know how to initiate it. I need to extract the password as noone knows it. It was installed a few years ago.

Edit: I know the IP address of the router

**Comment by Deantwo** [comment]
I just made a virtual CentOS in HyperV, so I don't actually know how to run Python on Windows.

Found a guide that might be useful for you, but I only just googled for it and haven't really read it myself.
Here: https://docs.python.org/3.3/using/windows.html

**Comment by adisone** [comment]
Ok, what I needed to do was start the command with "py" instead of "python". Not sure if it's python version related or the fact that I'm using windows 10.

Worked like a charm!
